services:
  - type: web
    name: fakenewsdetector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn fakenewsdetector.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
