services:
  - type: web
    name: fakenews-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn fakenewsdetector.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: fakenewsdetector.settings
      - key: SECRET_KEY
        value: your-very-secret-key-here
