# Generated by Django 5.1.7 on 2025-05-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
